# Generated by Django 2.2.6 on 2019-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=64)),
                ('input', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=64)),
                ('proof', models.CharField(max_length=162)),
            ],
        ),
    ]
