# Generated by Django 2.2.6 on 2019-11-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='idx',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
